Db 개발 완료
SeoulGreenJacket/Dr.Trash-BE pull request #15
Opened 2022-08-10 13:19 UTC by happyjamy

## 개발사항

### 이전 상황

#9 

### 개발 후 상황

DB 는 postgreSQL를 사용하였고 ORM을 사용하지 않고 pg libarary와 sql문 만으로 코드를 작성하였습니다.
close #9 

### 테스트 항목

- [ ] userCreate
- [ ] oauthCreate
- [ ] userFindByOauth
- [ ] userFindByUser_id

---

## 추가사항

database service에 sql 문을 작성할 것인지, 서비스 단에 작성할 것인지에 대한 논의가 필요할 것으로 사료됩니다.

2022-08-10 13:22 UTC, seheon99 commented
쿼리문을 어디에 작성할지 논의하고 머지해야겠네요

2022-08-10 13:47 UTC, seheon99 requested changes
수고하셨습니다! 코드 구조에 대해 다시 한 번 논의해봐요

2022-08-10 13:47 UTC, seheon99 commented on package.json
> +    "nest-pgpromise": "^1.1.0",
[nest-pgpromise](https://www.npmjs.com/package/nest-pgpromise) 는 deprecated 되었네요 [pg](https://www.npmjs.com/package/pg) 를 사용하는게 좋아보여요

2022-08-10 13:47 UTC, seheon99 commented on package.json
> +    "webpack-dev-server": "^4.9.3"
이건 어디에 사용하나요?

2022-08-10 13:47 UTC, seheon99 commented on src/auth/auth.controller.ts
> +  async logout(@Req() req, @Query() state) {
`state` 쿼리 지워주세요

2022-08-10 13:47 UTC, seheon99 commented on src/auth/auth.controller.ts
> +    private readonly authRepository: AuthRepository,
둘은 사용 안하는 것 같은데 맞나요?

2022-08-10 13:47 UTC, seheon99 commented on src/auth/auth.service.ts
> +  async login(user: User) {
`async` 지워주세용

2022-08-10 13:47 UTC, seheon99 commented on src/auth/strategy/jwt.strategy.ts
> +  }
`authRepository` 에서 찾아야하지 않나요?

2022-08-10 13:47 UTC, seheon99 commented on src/auth/strategy/jwt.strategy.ts
>  }
파일 분리해주세용

2022-08-10 13:47 UTC, seheon99 commented on src/database/database.service.ts
> +}
`Database` 모듈에서는 쿼리만 하고 나머지는 각각의 모듈에 있어야 하는게 맞다고 생각해요

2022-08-10 13:47 UTC, seheon99 commented on src/users/dto/create-user.dto.ts
> +export class CreateOauthDto {
OAuth!

2022-08-12 14:36 UTC, happyjamy commented on src/auth/auth.controller.ts
> +    private readonly authRepository: AuthRepository,
네네 맞아요 삭제 완료

2022-08-12 14:36 UTC, happyjamy commented on package.json
> +    "webpack-dev-server": "^4.9.3"
webpack-cli , webpack-dev-server 삭제 완료

2022-08-12 14:36 UTC, happyjamy commented on src/auth/auth.controller.ts
> +  async logout(@Req() req, @Query() state) {
이거 로그아웃 req로 해결 못하면 query로 하는 다른 방법하려고 넣어둔것 같은데 지금은 삭제 했어요~

2022-08-12 14:36 UTC, happyjamy commented on src/auth/auth.service.ts
> +  async login(user: User) {
삭제 완료

2022-08-12 14:36 UTC, happyjamy commented on src/auth/strategy/jwt.strategy.ts
> +  }
jwt 유효성 검사는 passport가 하고 저거는 유저 있는지 없는지만 검사해서 유저 return 거에용

2022-08-12 14:36 UTC, happyjamy commented on src/auth/strategy/jwt.strategy.ts
> +  }
`authRepository` 는 토큰 저장소

2022-08-12 14:36 UTC, happyjamy commented on src/auth/strategy/jwt.strategy.ts
>  }
분리 했어용

2022-08-12 14:36 UTC, happyjamy commented on src/users/dto/create-user.dto.ts
> +export class CreateOauthDto {
고쳤어요오!!!

2022-08-12 14:36 UTC, happyjamy commented on src/database/database.service.ts
> +}
### 데이터베이스 모듈을 없애고, 레포지토리 패턴을 통해 디비와 연결하는게 좋다고 생각해요.
 - 데이터베이스 모듈을 없애는 이유는, 네스트는 domain driven development 방식으로 개발하는 프레임워크이기 때문에, 디비는 도메인의 구성 요소이지 도메인 자체가 아니므로 없애려고 해요. 
 - 레포지토리 패턴을 사용하려는 이유는, 자주 변경되는 서비스(비즈니스 로직 레이어)와 데이터베이스를 연결하고 데이터를 조작하는 레포지토리(데이터 액세스 레이어)를 분리하여 각 레이어가 각자의 책임을 다하도록 분리하고, 어느 한 레이어의 변경이 다른 레이어에 전파되지 않도록 하기 위해서에요.
 - sql 쿼리문은 비즈니스 로직에 대한 부분보다는 데이터 액세스 로직에 대한 부분이라고 생각하기 때문에 서비스 파일이 아닌 레포지토리 파일에 있어야 한다고 생각해요. 

[reference1](https://stackoverflow.com/questions/15361103/3-layer-architecture-is-it-fine-to-put-sql-queries-in-business-layer)
[reference2](https://4z7l.github.io/2020/11/24/repository-pattern.html)
[reference3](https://docs.microsoft.com/ko-kr/dotnet/architecture/microservices/microservice-ddd-cqrs-patterns/infrastructure-persistence-layer-design)
[reference4](https://stackoverflow.com/questions/50312714/should-write-complex-query-in-repository-or-service-layer)

2022-08-13 05:27 UTC, happyjamy commented on src/database/database.service.ts
> +}
@seheon99 다른 의견 없으시다면 레포로 진행해도 될까요?!🥹

2022-08-13 07:01 UTC, seheon99 commented on src/database/database.service.ts
> +}
### 데이터베이스 모듈 삭제
Nest.js에서 모듈은 도메인을 나누는 방식이 아니라 기능과 책임이 분리된 객체를 싱글턴으로 제공하는 것이라고 생각해요. 하나의 고양이 도메인을 나타내는 `CatModule` 이 될 수도 있고 설정에 대한 기능을 제공하는 `ConfigModule` 이 될 수도 있는 것처럼요. 싱글턴 패턴은 데이터베이스와 백엔드를 연결시켜주는 객체에게 반드시 필요한 기능이고 싱글턴을 가장 쉽게 구현하는 방법이 모듈이라고 생각해요.

### 레포지토리 패턴
올려준 레퍼런스랑 데이터 게이트웨이, 데이터 맵퍼, 엑티브 레코드, DAO 같은 접근 패턴을 찾아보느라 늦었어요. 아직 데이터 맵퍼랑 레포지토리, DAO, ORM이 어떤 차이점이 있고 어떤 장단점이 있는지 더 찾아봐야될 것 같지만 데이터 접근과 데이터 처리를 레포지토리를 통해 나누는게 코드 구조와 가독성에 좋아보이네요

2022-08-14 06:17 UTC, seheon99 commented on src/database/database.service.ts
> +}
만들어서 풀리퀘 올릴게용

2022-08-14 08:09 UTC, happyjamy commented on package.json
> +    "nest-pgpromise": "^1.1.0",
nest-pg 말하시는 건가요 아님 그냥 pg 인가요??

2022-08-14 13:09 UTC, closed without merging