Refactor 36 db
SeoulGreenJacket/Dr.Trash-BE pull request #38
Opened 2022-08-17 18:15 UTC by happyjamy

## 개발사항

oauth 테이블이 사라지고 kakaoId 를 user 테이블에 컬럼으로 삽입하는 형식으로 db shema에 변화가 있었음.
1) 카카오 전략 파일에서 (name, kakaoId, thumbnail) 3개만 가져오게 변경 - provider 삭제
2) 유저 존재 여부 검사하는 findByOAuth 함수 findByKakaoId 로 변경하고 kakaoId 로 유저 찾음
3) user create 부분에서 createOAuth 함수를 삭제하고 서비스 함수에 바로 name, kakaoId, thumbnail 파라미터 전달

kakaoId 가 Long type 으로 전달되는 문제 때문에 코드 상의 kakaoId type 을 모두 bigint 로 변경하고
db의 kakaoId 컬럼 type을 bigint 로 변경.

### 이전 상황

#36  : 이슈번호

### 개발 후 상황

oauth 테이블이 사라지고 kakaoId 를 user 테이블에 컬럼으로 삽입하는 형식으로 db shema에 변화가 있었음.
1) 카카오 전략 파일에서 (name, kakaoId, thumbnail) 3개만 가져오게 변경 - provider 삭제
2) 유저 존재 여부 검사하는 findByOAuth 함수 findByKakaoId 로 변경하고 kakaoId 로 유저 찾음
3) user create 부분에서 createOAuth 함수를 삭제하고 서비스 함수에 바로 name, kakaoId, thumbnail 파라미터 전달

kakaoId 가 Long type 으로 전달되는 문제 때문에 코드 상의 kakaoId type 을 모두 bigint 로 변경하고
db의 kakaoId 컬럼 type을 bigint 로 변경.

### 테스트 항목

- [ ] create
- [ ] findByKakaoId
- [ ] findByUserId
- [ ] 카카오 로그인이 제대로 수행되는지
- [ ] 로그인 토큰 발급이 정상 작동 하는지

---

## 추가사항

카카오 로그인 드디어 완성 🥳🥺❤️

2022-08-18 10:24 UTC, seheon99 requested changes

2022-08-18 10:24 UTC, seheon99 commented on src/auth/auth.controller.ts
> +  @Post('refresh')
`refresh` 는 어플에서 넘어온 토큰을 저장하는게 아니라 서버에서 토큰을 생성해서 서버에 저장하고 유저에게 넘겨주는거라 `get` 이 맞다고 생각해요

2022-08-18 10:24 UTC, seheon99 commented on src/auth/auth.controller.ts
> +  @Post('logout')
`logout` 은 어플에서 보낸 토큰을 서버에서 삭제하니까 `delete` 로 처리하면 어떨까요

2022-08-19 10:08 UTC, happyjamy commented on src/auth/auth.controller.ts
> +  @Post('logout')
delete 로 처리하자는게 서비스함수 쓰지말고 authRepository delete로 바로 처리하자는건가요??

2022-08-19 10:12 UTC, happyjamy commented on src/auth/auth.controller.ts
> +  @Post('logout')
delete method 를 쓰자는 건가요?

2022-08-19 10:16 UTC, happyjamy commented on src/auth/auth.controller.ts
> +  @Post('refresh')
[HTTP/1.1 RFC](https://www.w3.org/Protocols/rfc2616/rfc2616-sec9.html)

2022-08-20 15:54 UTC, seheon99 commented on src/auth/auth.controller.ts
> +  @Post('refresh')
매번 다른 토큰이 전해진다는 점에서 캐싱 관련된 문제가 생길 수도 있겠네요.. `/auth/login/kakao` 이것도 `POST` 로 바꿔야 될 것 같아요

2022-08-20 16:05 UTC, seheon99 commented on src/auth/auth.controller.ts
> +  @Post('logout')
delete method 를 쓰자는 말이었어요. 데이터를 전송하거나 만들 때 사용하는 `POST` 보다는 데이터를 지울 때 사용하는 `DELETE` 가 완벽하게 표현하지는 못하지만 조금 더 자연스럽지 않은가 해서요

2022-08-21 07:41 UTC, seheon99 approved these changes
수고하셨습니다 👍

2022-08-21 07:42 UTC, merged