Enhance 41 users
SeoulGreenJacket/Dr.Trash-BE pull request #58
Opened 2022-08-31 06:17 UTC by happyjamy

## 개발사항

## ❗️마이페이지의 절반을 차지하는 유저정보 관련한 api를 완성하였습니다.

![스크린샷 2022-08-31 오후 2 25 34](https://user-images.githubusercontent.com/78072370/187598953-98e41d69-684b-4932-b828-c4c766bc5be7.png)

![스크린샷 2022-08-31 오후 2 25 41](https://user-images.githubusercontent.com/78072370/187603433-13db13c1-368d-4311-aab2-5a38777b2987.png)

### 기능명세

- `/users/{id}`
    - [ ] `GET` : 해당 User { id, name, thumbnail, point, userGrade, achievement, rank } 정보 가져오기
achievement[] data의 achievedAt key 취득하지 않았을 시 `null` 값으로 전송
```
  "achievements": [
    {
      "id": 21,
      "name": "첫 Dr.Trash 이용",
      "description": "처음 Dr.Trash를 이용한 사람"
      "achievedAt": "null"
    },
    {
      "id": 21,
      "name": "첫 Dr.Trash 이용",
      "description": "처음 Dr.Trash를 이용한 사람"
      "achievedAt": "2007-04-05T14:30Z"
    },
  ]
```
- [ ] `PATCH` : 해당 User { name, thumbnail } 변경
validation pipe 옵션에 `whitelist: true` `forbidNonWhitelisted: true` 설정해 다른 key 가 올 때 에러 발생

- [ ] `DELETE` : 해당 User 를 DB user table 에서 삭제

## ❗️상세랭킹페이지 관련 api를 완성하였습니다.

![스크린샷 2022-08-31 오후 2 26 02](https://user-images.githubusercontent.com/78072370/187603637-2013deea-d39e-412c-9c2a-c4956343ddb9.png)

### 기능 명세

-  `/users/rank`
    - [ ] `GET` : `limit` , `offset` query를 사용해 정렬 된 상태의  { userName, point } 를 필터링해 가져온다
`limit` default=10, `offset` default=0

#### ✔️ CheckUserId guard 를 만들었습니다.

Param 으로 들어온 userId 와 실제 userId (req.user) 를 비교해 
같을 시 true 다를 시 false 를 return 해 컨트롤러 함수의 실행 여부를 결정합니다.
❓false return 시 403 error throw
에러 메세지 작성을 해야할까? 

    

### 이전 상황

#41  : 이슈번호

### 테스트 항목

- [ ] findRankAll
- [ ] findOne
- [ ] update
- [ ] delete

---

## 추가사항

cache 관련한 파일은 commit 하지 않았습니다.
User decorator 달지 않았습니다.
type 으로 선언된 객체들 class 로 바꾸지 않았습니다.

위 3가지 일은 다른 브렌치에서 작업해서 pr 올리겠습니다~!

2022-09-03 07:50 UTC, seheon99 commented on package.json
> +    "cache-manager-redis-store": "^2.0.0",
이거 두개 삭제해도 되는거 맞나요?

2022-09-03 07:50 UTC, seheon99 commented on src/main.ts
> +
글로벌 파이프나 가드처럼 모든 엔드포인트에 영향을 주는 옵션은 최대한 피하고싶은데 각 엔드포인트에 `@UsePipes` 나 새로운 데코레이터를 만들어서 사용하는건 어떤가요

2022-09-04 14:36 UTC, happyjamy commented
conflict 해결하고 validation pipe 개별 적용 했어욧

2022-09-04 16:55 UTC, seheon99 requested changes

2022-09-04 16:55 UTC, seheon99 commented on src/users/entities/achievement.entity.ts
> +}
`user-response.dto.ts` 에서 `achievement` 를 `ValidateNested` 했는데 속성 정의를 안해줘도 되나요?

2022-09-05 13:38 UTC, seheon99 approved these changes
`Achievement` 엔티티는 `/achievement` 머지하고난 뒤에 삭제하면 될거같아요~

2022-09-05 13:39 UTC, merged