Refactor 60 cache수정
SeoulGreenJacket/Dr.Trash-BE pull request #61
Opened 2022-08-31 07:59 UTC by happyjamy

## 개발사항

**cache module** 에 export [ CacheService ] 추가

**cache service**
- addUserPoint 함수 추가
- getUserRank 인덱스가 0부터 시작하는 문제때문에 1을 더해서 return
- getUserRankList 함수 안 zRange 를 zRangeWithScores 로 변경해 score 도 같이 return 하게 변경 

close #60 

### 이전 상황

#60  : 이슈번호

### 테스트 항목

- [ ] migrateUsersPoint
- [ ] addUserPoint
- [ ] getUserRankList
- [ ] updateUserPoint

2022-08-31 09:33 UTC, seheon99 requested changes
레디스에 업데이트나 추가하는 과정을 동기적으로 처리할 필요가 있을까요?

2022-08-31 09:46 UTC, happyjamy commented
업데이트하고 추가 하는 함수를 다른 곳에서 단독으로 쓰진 않을 것 같아서 비동기함수로 쓰고 싶어서 저렇게 짰어요!

2022-09-03 07:50 UTC, seheon99 commented on src/cache/cache.service.ts
> +        });
`zAdd` 를 `Promise.all` 로 처리하려면 반환해줘야하지 않나요?

2022-09-03 07:50 UTC, happyjamy commented on src/cache/cache.service.ts
> +        });
맞습니다~

2022-09-03 08:02 UTC, seheon99 commented on src/cache/cache.service.ts
> +    );
이렇게 바꾸는건 어떨까요

```javascript
return Promise.all(
  usersPoint.map(({ id, point }) => {
    return this.client.zAdd('user-point', {
      score: point,
      value: id.toString(),
    });
  }),
);
```

2022-09-03 08:43 UTC, happyjamy commented on src/cache/cache.service.ts
> +    );
`Promise.all(
  usersPoint.map(({ id, point }) => {
    return this.client.zAdd('user-point', {
      score: point,
      value: id.toString(),
    });
  }),
);`

혹시 결과를 return 안해도 되면 이렇게 써도 괜찮을까요??

2022-09-03 08:47 UTC, seheon99 commented on src/cache/cache.service.ts
> +    );
결과를 반환 안하면 `Promise.all` 로 묶을 필요가 없지않나요?

2022-09-03 08:50 UTC, happyjamy commented on src/cache/cache.service.ts
> +    );
안묶으면 배열 안에 프라미스를 동기적으로 해결하고 묶으면 프라미스를 비동기적으로 해결하는 차이 아닌가요? 저는 그렇게 아는디

2022-09-03 08:59 UTC, seheon99 commented on src/cache/cache.service.ts
> +    );
```javascript
await Promise.all(
  usersPoint.map(({ id, point }) => {
    return this.client.zAdd('user-point', {
      score: point,
      value: id.toString(),
    });
  }),
);
```

이러면 될거같아요

2022-09-04 14:15 UTC, happyjamy commented
error 함수 안에서 바로 처리하게 짰습니다

2022-09-04 17:02 UTC, seheon99 commented
왜 `async` 랑 `await` 을 사용하지 않나요

2022-09-05 03:27 UTC, happyjamy commented
promise.all 에 바로 catch로 잡았어요
try catch 로 쓰려면 모듈에 로직을 써야해서요

2022-09-05 03:36 UTC, seheon99 commented
`.then.catch` 로 처리하던 `try { await } catch` 로 처리하던 다른 코드와 일관적이게 처리하는게 좋지않을까요

2022-09-05 08:02 UTC, seheon99 approved these changes

2022-09-05 08:03 UTC, merged